Feature/sweetcard
SoftRyzen-internship/de-tort pull request #15
Opened 2024-02-01 08:37 UTC by sergio-nezhigay

картка смаколики

2024-02-01 14:59 UTC, opanchen requested changes

2024-02-01 14:59 UTC, opanchen commented on src/components/Example.tsx
> +        bgSrc="/images/cookies-@x2.jpg"
при        ` bgSrc="/images/pasta-@x2.jpg"`  зображення не відповідає макету (https://prnt.sc/XsXOKBbvxPFe)

переглянь реалізацію тумби з зображенням і краще в тестовому компоненті зроби список цих карток для більш зручної перевірки всіх  6-ти кейсів

+ зображення краще викачевати відразу x2 в webP і, якщо оптимізуєш через скуш, обирати 95-99%, інакше дуже сильно втрачають в якості після додаткової оптимізації некстом

2024-02-01 14:59 UTC, opanchen commented on src/components/ui/SweetsCard/SweetsCard.tsx
> +      className="block h-[320px] md:w-[336px] md:h-[364px] xl:w-[384px] xl:h-[412px] rounded-3xl overflow-hidden w-full text-[28px] leading-normal relative"
якщо дозволяти тумбі тягнутися в ширину на мобільній версії, при ховері зображення налазить на текст (https://prnt.sc/6fe6QBP1qKSF)

можливо, є сенс зменшити скейл, але це треба перевіряти на всіх варіантах зображень, а не тільки на першому

2024-02-01 14:59 UTC, opanchen commented on src/components/ui/SweetsCard/SweetsCard.tsx
> +        className="object-cover w-full h-full hover:scale-110 focus:scale-110 transition-transform"
відловлювати ховер треба не на зображенні, а на самій картці товару (лінку) - інакше при ховері на текст зум втрачається

2024-02-01 14:59 UTC, opanchen commented on src/components/Example.tsx
> +        name="Печиво"
занеси дані по цим карткам в json, будь ласка - так буде простіше перевірити їх всі + легше потім працювати з цими компонентами

2024-02-01 16:19 UTC, sergio-nezhigay commented on src/components/ui/SweetsCard/SweetsCard.tsx
> +      className="block h-[320px] md:w-[336px] md:h-[364px] xl:w-[384px] xl:h-[412px] rounded-3xl overflow-hidden w-full text-[28px] leading-normal relative"
я поки 1 картку роблю. це не видно, простіше scale скоретувати під час підключення секції

2024-02-01 16:21 UTC, opanchen commented on src/components/ui/SweetsCard/SweetsCard.tsx
> +      className="block h-[320px] md:w-[336px] md:h-[364px] xl:w-[384px] xl:h-[412px] rounded-3xl overflow-hidden w-full text-[28px] leading-normal relative"
тоді зроби список карток, щоб можна було їх нормально перевірити

2024-02-01 17:02 UTC, sergio-nezhigay commented on src/components/ui/SweetsCard/SweetsCard.tsx
> +      className="block h-[320px] md:w-[336px] md:h-[364px] xl:w-[384px] xl:h-[412px] rounded-3xl overflow-hidden w-full text-[28px] leading-normal relative"
ми ж вже про секцію домовились

2024-02-02 08:58 UTC, Basilika-draconum approved these changes

2024-02-02 10:31 UTC, opanchen approved these changes

2024-02-02 10:33 UTC, merged