Third merge
SoftRyzen-internship/de-tort pull request #33
Opened 2024-02-06 15:00 UTC by Basilika-draconum

Виправили попередні баги і коментарі. Зібрали сторінку основну(окрім секції начинки). Створили і зібрали сторінку /cakes. Додали в сирому вигляді мета-теги. Проблема з висотою картки на сторінці торів -відома - в процесі вирішення.

2024-02-06 21:36 UTC, nadiakhoptiuk requested changes
https://prnt.sc/0S2pH0Q99vK-
кнопка меню при ховері

також варто розділити компоненти в папці sections по сторінках, а також в папці data - статичні дані. їх уже стає багато, а буде ще більше

https://prnt.sc/KF2q9-g_K04j - ось тут треба зробити однаковий бордер, 2 або 1

2024-02-06 21:36 UTC, nadiakhoptiuk commented on src/sections/About/About.tsx
> +          <div className="smOnly:mb-10 flex flex-col gap-6 md:gap-8 xl:gap-10 xl:max-w-[416px]">
немає сенсу робити обгортку тут, оскільки можна обійтися просто маржинами, всі ці елементи знаходяться один під одним на всіх екранах

2024-02-06 21:36 UTC, nadiakhoptiuk commented on src/data/meta-constants.json
> +  "title": "Кондитерська De-tort",
треба точно дізнатися їх назву, щоб було однаково

2024-02-06 21:36 UTC, nadiakhoptiuk commented on src/data/meta-constants.json
> +  "keywords": "торт, печиво, капкейк, чизкейк",
сюди можна додати більше категорій, з меню і тд

2024-02-06 21:36 UTC, nadiakhoptiuk commented on src/components/ui/ToppingCard/ToppingCard.tsx
> +export const ToppingCard: React.FC<ToppingCardProps> = ({
тут тінь все таки має інший вид, ніж на макеті.
drop-shadow не спрацювало?

2024-02-06 21:36 UTC, nadiakhoptiuk commented on src/components/ui/AchievementCard/AchievementCard.tsx
>        <p className="font-fixel absolute top-[-18px] right-6 border-color-accent-primary border-2 text-color-accent-primary bg-color-bg-white px-2 py-0.5 rounded font-medium text-[24px] leading-[1.33]
тут всю пешку слід замінити на спан

і думаю, дів всередині можна було б не додавати, суто лішку зі стилями

2024-02-06 21:36 UTC, nadiakhoptiuk commented on src/components/base/SliderNav/SliderNav.tsx
> +        <button
може їх мепнути?, тут майже все однакове

2024-02-06 21:36 UTC, nadiakhoptiuk commented on src/components/base/Slider/Slider.tsx
> +        grabCursor={true}
одразу пишу - прибрати лоадінг лейзі для 1 слайду

2024-02-06 21:37 UTC, nadiakhoptiuk approved these changes

2024-02-06 21:37 UTC, merged

2024-02-07 09:21 UTC, sergio-nezhigay commented on src/app/cakes/page.tsx
> +export default async function Page() {
виправлено ПР36

2024-02-07 09:25 UTC, sergio-nezhigay commented on src/sections/About/About.tsx
> +          <div className="smOnly:mb-10 flex flex-col gap-6 md:gap-8 xl:gap-10 xl:max-w-[416px]">
замінив flex на space-y. Це достатньо чи убирати map? виправлено ПР36.

2024-02-07 09:25 UTC, sergio-nezhigay commented on src/data/meta-constants.json
> +  "keywords": "торт, печиво, капкейк, чизкейк",
виправлено ПР36

2024-02-07 09:27 UTC, TrueMolni commented on src/components/ui/ToppingCard/ToppingCard.tsx
> +export const ToppingCard: React.FC<ToppingCardProps> = ({
В макеті показувало не ту тінь, виправив

2024-02-07 09:29 UTC, TrueMolni commented on src/components/ui/AchievementCard/AchievementCard.tsx
>        <p className="font-fixel absolute top-[-18px] right-6 border-color-accent-primary border-2 text-color-accent-primary bg-color-bg-white px-2 py-0.5 rounded font-medium text-[24px] leading-[1.33]
Краще дів, бо від свайпера йде lauout <li>, було лішка в лішці

2024-02-07 10:00 UTC, TrueMolni commented on src/components/base/SliderNav/SliderNav.tsx
> +        <button
Мепнув

2024-02-07 10:14 UTC, TrueMolni commented on src/components/base/Slider/Slider.tsx
> +        grabCursor={true}
Зробив

2024-02-07 12:41 UTC, opanchen commented on src/layout/Footer/Footer.tsx
> +  const { soft_ryzen, info } = data;
+++

2024-02-07 12:42 UTC, opanchen commented on src/sections/HeroCakes/HeroCakes.tsx
> +          className="mb-10 w-[320px] text-center m-auto md:w-[383px] xl:mb-[60px] xl:w-[585px]"
+++
залишив шрифт для таблета 44px, як на дизайні головної сторінки

2024-02-07 12:44 UTC, opanchen commented on src/components/ui/CardCakes/CardCakes.tsx
> +      <Link href={slug}>
+++

2024-02-07 12:44 UTC, opanchen commented on src/components/ui/CardCakes/CardCakes.tsx
> +          height={360}
+++

2024-02-07 12:45 UTC, opanchen commented on src/components/ui/CardCakes/CardCakes.tsx
> +          className="object-cover w-full h-full xl:hidden"
в процесі, написав комент в макеті - чекаємо

2024-02-07 12:45 UTC, opanchen commented on src/components/ui/CardCakes/CardCakes.tsx
> +      <div className="hidden group-hover:flex notXl:invisible absolute bottom-10 left-[147.5px]">
+++
реалізував через прозорість

2024-02-07 15:05 UTC, nadiakhoptiuk commented on src/components/ui/CardCakes/CardCakes.tsx
> +      <Link href={slug}>
все чудово, лише варто прибрати ефект з кнопки, бо вона по суті не інтерактивна сама по собі, щоб не вводити користувача в оману, адже вона просто спан, ну і з клавіатури не обирається

2024-02-07 15:17 UTC, nadiakhoptiuk commented on src/components/ui/ToppingCard/ToppingCard.tsx
> +export const ToppingCard: React.FC<ToppingCardProps> = ({
тінь супер, але самі фотки не ок - треба викачати png і пробувати підігнати їх під розмір, або прямо обрізати до тарілки..
замовник це все повинен робити сам, це узгоджено, він буде вантажити в адмінку просто тарілки у форматі png
https://prnt.sc/udw5WscJGWBL

2024-02-07 15:19 UTC, nadiakhoptiuk commented on src/components/base/SliderNav/SliderNav.tsx
> +        <button
чудово, але іконку стрілку вправо треба видалити

2024-02-07 16:00 UTC, TrueMolni commented on src/components/ui/ToppingCard/ToppingCard.tsx
> +export const ToppingCard: React.FC<ToppingCardProps> = ({
Зробив

2024-02-07 16:01 UTC, TrueMolni commented on src/components/base/SliderNav/SliderNav.tsx
> +        <button
Видалив

2024-02-07 16:24 UTC, sergio-nezhigay commented on src/components/ui/CardCakes/CardCakes.tsx
> +      <Link href={slug}>
виправлено ПР41

2024-02-07 16:24 UTC, sergio-nezhigay commented on src/sections/About/About.tsx
> +          <div className="smOnly:mb-10 flex flex-col gap-6 md:gap-8 xl:gap-10 xl:max-w-[416px]">
виправлено ПР41