Seventh
SoftRyzen-internship/de-tort pull request #65
Opened 2024-02-15 16:09 UTC by Basilika-draconum

Виправили частину багів.
З попереднього пр не виправили зауваження по формі(з чекбоксами в основному коментарі),Також не зробили модалку яка тягнеться до 480.
Додали валідацію у форму. Прикрутили нові сторінки з солодощами і відповідним контентом.
Додали сторінку для кав'ярень, але повністю ще не наповнили контентом.

2024-02-15 17:01 UTC, nadiakhoptiuk requested changes
- [x] потрібно робити картки начинок у модалці з висотою auto, хтось зафіксував висоту для p всередині, для діва зовні і для картки. і тоді виходить ось це: 
https://prnt.sc/PJOXMAc_shMJ

помилки валідації :
- [ ] https://prnt.sc/ebhsm6xdUO2r /cakes
- [ ] https://prnt.sc/MeJDu-V_DENL Головна
- [ ] https://prnt.sc/JyfhtChPMRff динамічна сторінка торта, слайдер
- [ ] https://prnt.sc/IxIbn1QpEEYs динамічна сторінка торта
- [ ] https://prnt.sc/MdI3efHy1mXD https://prnt.sc/HIDasl3mRo7K динамічна сторінка смаколиків
- [ ] https://prnt.sc/kD4IXcMtTeej 
- [ ] https://prnt.sc/AN5EZSV4lO_U

Інше:
- [ ] https://prnt.sc/CqZ1a74N0F4I - точковий баг
- [ ] https://prnt.sc/gujSYXHeq5Kr - одна з усіх картинок цієї шаблонної сторінки чомусь сплюснута з боків (перевірити з точки зору object-fit: cover;)
- [ ] https://prnt.sc/EnwOH9J3TVvx аріа-лейбли та альти повинні бути мовою сайту

2024-02-15 17:01 UTC, nadiakhoptiuk commented on src/components/ui/Field/types.ts
> +  slug: CakeSlug | SweetsSlug;
вище за опціональні перемістити

2024-02-16 11:14 UTC, nadiakhoptiuk approved these changes
- [ ] https://prnt.sc/IPUEKjzYxL7j - трохи тут заблизько до інпута, на макеті більший відступ

2024-02-16 11:14 UTC, nadiakhoptiuk commented on src/requests/fetchB2bPageData.ts
> +    console.log("fetch B2B-page data error: ", error);
логи не забути прибрати

2024-02-16 11:16 UTC, merged

2024-02-16 14:26 UTC, sergio-nezhigay commented on src/components/ui/Field/types.ts
> +  slug: CakeSlug | SweetsSlug;
зроблено

2024-02-16 15:21 UTC, sergio-nezhigay commented on src/components/ui/Field/types.ts
> +  slug: CakeSlug | SweetsSlug;
перемістив

2024-02-16 15:22 UTC, sergio-nezhigay commented on src/actions/telegram.ts
> +    console.log("Sending:", response);
убрав